["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "lib"


["protostar.build"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.test"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
incentivizedERC20 = [
    "./contracts/protocol/tokenization/base/incentivized_erc20.cairo",
]

