["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
a_token = [
    "contracts/protocol/tokenization/a_token.cairo",
]
pool = [
    "./contracts/protocol/pool/pool.cairo",
]


incentivized_erc20_library = [
    "./contracts/protocol/tokenization/base/incentivized_erc20_library.cairo",
]
scaled_balance_token = [
    "./contracts/protocol/tokenization/base/scaled_balance_token.cairo",
]
scaled_balance_token_library = [
    "./contracts/protocol/tokenization/base/scaled_balance_token_library.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]